name: Build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23

      - name: Current system
        run: nix eval --impure --expr 'builtins.currentSystem'

      - name: Cross-compile
        run: ./build-flake.sh
